/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.zabalburu.daw1.tmdb.panels;

import info.movito.themoviedbapi.model.core.Movie;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons;
import jiconfont.swing.IconFontSwing;
import mdlaf.MaterialLookAndFeel;
import mdlaf.themes.MaterialOceanicTheme;
import org.zabalburu.daw1.tmdb.TMDB;
import org.zabalburu.daw1.tmdb.servicio.TMDBServicio;

/**
 *
 * @author ichueca
 */
public class PnlPeliculas extends javax.swing.JPanel {

    private List<Movie> peliculas = new ArrayList<>();

    public void setPeliculas(List<Movie> peliculas) {
        this.peliculas = peliculas;
        JPanel pnlPelis = new JPanel();
        pnlPelis.setLayout(new BoxLayout(pnlPelis, BoxLayout.X_AXIS));
        pnlPelis.add(Box.createHorizontalGlue());
        pnlPelis.add(Box.createHorizontalStrut(10));
        for (int i = 0; i < peliculas.size(); i++) {
            pnlPelis.add(new PnlPelicula(peliculas.get(i)));
            this.add(Box.createHorizontalStrut(10));
        }
        pnlPelis.add(Box.createHorizontalStrut(5));
        pnlPelis.add(Box.createHorizontalGlue());
        this.setLayout(new BorderLayout());
        JScrollPane jsp = new JScrollPane(pnlPelis);
        this.setPreferredSize(new Dimension(1000, 300));
        this.add(jsp);
    }

    /**
     * Creates new form PnlPeliculas
     */
    public PnlPeliculas() {
        this(new ArrayList<>());
    }

    public PnlPeliculas(List<Movie> peliculas) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(160, 230));
        setMinimumSize(new java.awt.Dimension(160, 230));
        setPreferredSize(new java.awt.Dimension(160, 230));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(new MaterialLookAndFeel(new MaterialOceanicTheme()));
            IconFontSwing.register(GoogleMaterialDesignIcons.getIconFont());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(TMDB.class.getName()).log(Level.SEVERE, null, ex);
        }
        JFrame frm = new JFrame();
        frm.setSize(1000,300);
        TMDBServicio servicio = new TMDBServicio();
        PnlPeliculas pnl = new PnlPeliculas();
        pnl.setPeliculas(servicio.getNowPlaying());
        frm.add(pnl);
        frm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //frm.setSize(pnl.getPreferredSize());
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
