/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.zabalburu.daw1.tmdb.panels;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.UIManager;
import jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons;
import jiconfont.swing.IconFontSwing;
import mdlaf.MaterialLookAndFeel;
import mdlaf.themes.MaterialOceanicTheme;
import org.zabalburu.daw1.tmdb.modelo.Usuario;
import org.zabalburu.daw1.tmdb.servicio.TMDBServicio;

/**
 *
 * @author ichueca
 */
public class PnlUsuario extends javax.swing.JPanel {

    private Usuario usuario = null;

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        avtUsuario.setIcon(new ImageIcon("images/" + usuario.getImagen()));
    }

    /**
     * Creates new form PnlUsuario
     */
    public PnlUsuario() {
        initComponents();
        if (usuario == null) {
            avtUsuario.setIcon(new ImageIcon("images/no_image.jpg"));
        } else {
            avtUsuario.setIcon(new ImageIcon("images/" + usuario.getImagen()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTituo = new javax.swing.JLabel();
        avtUsuario = new org.zabalburu.daw1.tmdb.componentes.ImageAvatar();
        txtBuscar = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.GridBagLayout());

        lblTituo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituo.setText("The Movie Database");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblTituo, gridBagConstraints);

        avtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        avtUsuario.setBorderSize(0);
        avtUsuario.setMaximumSize(new java.awt.Dimension(60, 60));
        avtUsuario.setMinimumSize(new java.awt.Dimension(60, 60));
        avtUsuario.setName(""); // NOI18N
        avtUsuario.setPreferredSize(new java.awt.Dimension(60, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 11, 5, 5);
        add(avtUsuario, gridBagConstraints);

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscar.setText("Buscar Película");
        txtBuscar.setPreferredSize(new java.awt.Dimension(75, 40));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtBuscar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        if (txtBuscar.getText().equals("Buscar Película")) {
            txtBuscar.setFont(new Font("Segoe UI", Font.PLAIN, 18));
            txtBuscar.setText("");
            txtBuscar.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    public static void main(String[] args) {
        TMDBServicio servicio = new TMDBServicio();
        try {
            UIManager.setLookAndFeel(new MaterialLookAndFeel(
                    new MaterialOceanicTheme()));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        IconFontSwing.register(GoogleMaterialDesignIcons.getIconFont());

        JFrame frm = new JFrame();
        PnlUsuario pnl = new PnlUsuario();
        pnl.setUsuario(servicio.getUsuario(1));
        frm.add(pnl, BorderLayout.NORTH);
        frm.setSize(new Dimension(1000, 200));
        frm.setLocationRelativeTo(null);
        frm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frm.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.zabalburu.daw1.tmdb.componentes.ImageAvatar avtUsuario;
    private javax.swing.JLabel lblTituo;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
