/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.zabalburu.daw1.tmdb.views;

import info.movito.themoviedbapi.model.core.Genre;
import info.movito.themoviedbapi.model.core.Movie;
import info.movito.themoviedbapi.model.movies.MovieDb;
import java.awt.Dimension;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons;
import jiconfont.swing.IconFontSwing;
import mdlaf.MaterialLookAndFeel;
import mdlaf.themes.MaterialOceanicTheme;
import javax.swing.JScrollPane;
import org.zabalburu.daw1.tmdb.TMDB;
import org.zabalburu.daw1.tmdb.componentes.JLabelTransparent;
import org.zabalburu.daw1.tmdb.componentes.RoundedImage;
import org.zabalburu.daw1.tmdb.componentes.VoteJLabel;
import org.zabalburu.daw1.tmdb.panels.CastPanel;
import org.zabalburu.daw1.tmdb.servicio.TMDBServicio;

/**
 *
 * @author IñigoChueca
 */
public class FrmDetallePelicula extends javax.swing.JFrame {
    private MovieDb pelicula;
    private CastPanel cp;
    
    
    /**
     * Creates new form FrmDetallePelicula
     */
    public FrmDetallePelicula(MovieDb pelicula) {
        this.pelicula = pelicula;
        cp = new CastPanel(pelicula.getCredits().getCast());
        initComponents();
        
        
        try {
            URL url = new URI("https://image.tmdb.org/t/p/w342/"
                    + pelicula.getPosterPath()).toURL();
            Icon imag = new ImageIcon(url);
            URL urlFondo = new URI("https://image.tmdb.org/t/p/w1280/"
                    + pelicula.getBackdropPath()).toURL();
            Icon imagFondo = new ImageIcon(urlFondo);
            lblFondo.setIcon(imagFondo);
            lblPoster.setIcon(imag);
            lblPoster.setMinimumSize(new Dimension(imag.getIconWidth(), imag.getIconHeight()));
            lblPoster.setPreferredSize(new Dimension(imag.getIconWidth(), imag.getIconHeight()));
            lblPoster.setSize(new Dimension(imag.getIconWidth(), imag.getIconHeight()));
            ((JLabelTransparent) lblFondo).setAlpha(0.2);
        } catch (URISyntaxException ex) {
            Logger.getLogger(FrmDetallePelicula.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(FrmDetallePelicula.class.getName()).log(Level.SEVERE, null, ex);
        }
        lblSinposis.setText("<html>" + pelicula.getOverview() + "</html>");
        lblVoto.setPorcentaje((int) (pelicula.getVoteAverage()*10));
        String fecha = pelicula.getReleaseDate();
        lblTitulo.setText(pelicula.getTitle() + " (" + fecha.substring(0,4) + ")");
        fecha = fecha.substring(8) + "/" + fecha.substring(5,7) + "/" + fecha.substring(0,4);
        String generos = fecha + " • "; 
        
        for(Genre g : pelicula.getGenres()){
            generos += g.getName() + ", ";
        }
        generos = generos.substring(0, generos.length()-2);
        lblGeneros.setText(generos + " • " + toTime(pelicula.getRuntime()));
        lblCalificacion.setText(getCalificacion());
        
    }
    
    private String toTime(int minutes){
        int horas = minutes / 60;
        int minutos = minutes % 60;
        return horas + "h " + ((minutos<10)?"0":"") + minutos + "m";
    }
    
    private String getCalificacion(){
        String calif = pelicula.getReleaseDates()
                .getResults()
                .stream()
                .filter(ri -> ri.getIso31661().equalsIgnoreCase("ES"))
                .map(rd -> rd.getReleaseDates().get(0).getCertification())
                .findAny()
                .orElse("");
        return calif.isEmpty() ? "S.C." : calif;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblVoto = new VoteJLabel();
        lblS = new javax.swing.JLabel();
        lblSinposis = new javax.swing.JLabel();
        lblGeneros = new javax.swing.JLabel();
        lblCalificacion = new javax.swing.JLabel();
        lblPoster = new RoundedImage();
        jspCast = new JScrollPane(cp);
        lblCast = new javax.swing.JLabel();
        lblFondo = new JLabelTransparent();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 513));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitulo.setText("Título (Año)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(lblTitulo, gridBagConstraints);

        lblVoto.setText(" ");
        lblVoto.setMaximumSize(new java.awt.Dimension(40, 40));
        lblVoto.setMinimumSize(new java.awt.Dimension(40, 40));
        lblVoto.setPorcentaje(7);
        lblVoto.setPreferredSize(new java.awt.Dimension(40, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(lblVoto, gridBagConstraints);

        lblS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblS.setText("Sinopsis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(lblS, gridBagConstraints);

        lblSinposis.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSinposis.setText("Sinopsis");
        lblSinposis.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(lblSinposis, gridBagConstraints);

        lblGeneros.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblGeneros.setText("Generos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 2);
        jPanel1.add(lblGeneros, gridBagConstraints);

        lblCalificacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCalificacion.setText("jLabel1");
        lblCalificacion.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createEmptyBorder(3, 5, 3, 5)));
        lblCalificacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 2);
        jPanel1.add(lblCalificacion, gridBagConstraints);

        lblPoster.setText("roundedImage1");
        lblPoster.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblPoster.setMaximumSize(new java.awt.Dimension(349, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        jPanel1.add(lblPoster, gridBagConstraints);

        jspCast.setMinimumSize(new java.awt.Dimension(800, 230));
        jspCast.setPreferredSize(new java.awt.Dimension(800, 230));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jspCast, gridBagConstraints);

        lblCast.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCast.setText("Reparto Principal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(lblCast, gridBagConstraints);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 620);

        lblFondo.setMinimumSize(new java.awt.Dimension(830, 449));
        lblFondo.setName(""); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 1100, 620);

        setSize(new java.awt.Dimension(1121, 647));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            UIManager.setLookAndFeel(new MaterialLookAndFeel(new MaterialOceanicTheme()));
            IconFontSwing.register(GoogleMaterialDesignIcons.getIconFont());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(TMDB.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Movie m = new TMDBServicio().getNowPlaying().get(0);
                new FrmDetallePelicula(new TMDBServicio().getPelicula(m.getId())).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jspCast;
    private javax.swing.JLabel lblCalificacion;
    private javax.swing.JLabel lblCast;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblGeneros;
    private RoundedImage lblPoster;
    private javax.swing.JLabel lblS;
    private javax.swing.JLabel lblSinposis;
    private javax.swing.JLabel lblTitulo;
    private VoteJLabel lblVoto;
    // End of variables declaration//GEN-END:variables
}
