/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.zabalburu.daw1.tmdb.views;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons;
import jiconfont.swing.IconFontSwing;
import org.zabalburu.daw1.tmdb.modelo.Usuario;
import org.zabalburu.daw1.tmdb.servicio.TMDBServicio;
import org.zabalburu.daw1.util.Colores;

/**
 *
 * @author ichueca
 */
public class FrmLogin extends javax.swing.JFrame {
    private TMDBServicio servicio = new TMDBServicio();

    public void setServicio(TMDBServicio servicio) {
        this.servicio = servicio;
    }
    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        lblLogo.setIcon(IconFontSwing.buildIcon(
                GoogleMaterialDesignIcons.PERSON,
                100, Colores.GREEN));
        lblRegistro.setForeground(Colores.GREEN);
        //this.getRootPane().setDefaultButton(btnEntrar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlDatos = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblRegistro = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        pwdPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");

        pnlLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 50, 0, 50));
        pnlLogo.setLayout(new javax.swing.BoxLayout(pnlLogo, javax.swing.BoxLayout.LINE_AXIS));

        lblLogo.setPreferredSize(new java.awt.Dimension(180, 0));
        pnlLogo.add(lblLogo);

        getContentPane().add(pnlLogo, java.awt.BorderLayout.LINE_START);

        pnlDatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 50));
        pnlDatos.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("Identifíquese con su usuario y contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(14, 9, 9, 9);
        pnlDatos.add(lblTitulo, gridBagConstraints);

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsuario.setName("txtUsuario"); // NOI18N
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teclaPulsada(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(14, 9, 9, 9);
        pnlDatos.add(txtUsuario, gridBagConstraints);

        btnEntrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.setName("btnEntrar"); // NOI18N
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(14, 9, 9, 9);
        pnlDatos.add(btnEntrar, gridBagConstraints);

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setName("btnSalir"); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(14, 9, 9, 9);
        pnlDatos.add(btnSalir, gridBagConstraints);

        lblRegistro.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblRegistro.setText("¿Todavia no tiene usuario? Regístrese");
        lblRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRegistroMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(14, 9, 9, 9);
        pnlDatos.add(lblRegistro, gridBagConstraints);

        lblError.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 51));
        lblError.setText(" ");
        lblError.setToolTipText("");
        lblError.setName("lblError"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(14, 9, 9, 9);
        pnlDatos.add(lblError, gridBagConstraints);

        pwdPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pwdPassword.setName("pwdPassword"); // NOI18N
        pwdPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teclaPulsada(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(14, 9, 9, 9);
        pnlDatos.add(pwdPassword, gridBagConstraints);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(832, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String usuario = txtUsuario.getText();
        String password = new String(pwdPassword.getPassword());
        if (usuario.isBlank()){
            lblError.setText("Debe especificarse el usuario");
            txtUsuario.requestFocus();
            return;
        }
        if (password.isBlank()){
            lblError.setText("Debe especificarse la contraseña");
            pwdPassword.requestFocus();
            return;
        }
        Usuario usu = servicio.login(usuario, password);
        if (usu == null){
            lblError.setText("Usuario / contraseña erróneos");
            txtUsuario.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, 
                "Bienvenido a la Aplicación");
            this.dispose();
            FrmPrincipal frm = new FrmPrincipal();
            frm.setUsuario(usu);
            frm.setVisible(true);
            
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void teclaPulsada(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teclaPulsada
        lblError.setText(" ");
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (evt.getSource() == txtUsuario){
                pwdPassword.requestFocus();
            } else if (evt.getSource() == pwdPassword){
                btnEntrar.doClick();
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            btnSalir.doClick();
        }
    }//GEN-LAST:event_teclaPulsada

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if (JOptionPane.showConfirmDialog(
            this,
            "Realmente desea salir?",
            "Salir",
            JOptionPane.YES_NO_OPTION)
            == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void lblRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistroMousePressed
        new FrmRegistro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblRegistroMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
