/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.zabalburu.daw1.tmdb.views;

import javax.swing.UIManager;
import mdlaf.MaterialLookAndFeel;
import mdlaf.themes.MaterialOceanicTheme;
import org.zabalburu.daw1.tmdb.modelo.Usuario;
import org.zabalburu.daw1.tmdb.servicio.TMDBServicio;

/**
 *
 * @author ichueca
 */
public class FrmPrincipal extends javax.swing.JFrame {
    private static TMDBServicio servicio = new TMDBServicio();
    
    private Usuario usuario;

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        pnlUsuario.setUsuario(usuario);
    }
    
    
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        pnlCartelera.setPeliculas(servicio.getNowPlaying());
        pnlPopulares.setPeliculas(servicio.getPopular());
        pnlValoradas.setPeliculas(servicio.getTopRated());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlUsuario = new org.zabalburu.daw1.tmdb.panels.PnlUsuario();
        pnlPeliculas = new javax.swing.JPanel();
        lblCartelerar = new javax.swing.JLabel();
        pnlCartelera = new org.zabalburu.daw1.tmdb.panels.PnlPeliculas();
        lblPopulares = new javax.swing.JLabel();
        pnlPopulares = new org.zabalburu.daw1.tmdb.panels.PnlPeliculas();
        lblValoradas = new javax.swing.JLabel();
        pnlValoradas = new org.zabalburu.daw1.tmdb.panels.PnlPeliculas();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("The Movie Database");
        getContentPane().add(pnlUsuario, java.awt.BorderLayout.PAGE_START);

        pnlPeliculas.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlPeliculas.setLayout(new java.awt.GridBagLayout());

        lblCartelerar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblCartelerar.setText("En Cartelera");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlPeliculas.add(lblCartelerar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlPeliculas.add(pnlCartelera, gridBagConstraints);

        lblPopulares.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblPopulares.setText("Populares");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlPeliculas.add(lblPopulares, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlPeliculas.add(pnlPopulares, gridBagConstraints);

        lblValoradas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblValoradas.setText("Mejor Valoradas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlPeliculas.add(lblValoradas, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlPeliculas.add(pnlValoradas, gridBagConstraints);

        getContentPane().add(pnlPeliculas, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1387, 941));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new MaterialLookAndFeel(
                    new MaterialOceanicTheme()));
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPrincipal p = new FrmPrincipal();
                p.setUsuario(servicio.getUsuario(1));
                p.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCartelerar;
    private javax.swing.JLabel lblPopulares;
    private javax.swing.JLabel lblValoradas;
    private org.zabalburu.daw1.tmdb.panels.PnlPeliculas pnlCartelera;
    private javax.swing.JPanel pnlPeliculas;
    private org.zabalburu.daw1.tmdb.panels.PnlPeliculas pnlPopulares;
    private org.zabalburu.daw1.tmdb.panels.PnlUsuario pnlUsuario;
    private org.zabalburu.daw1.tmdb.panels.PnlPeliculas pnlValoradas;
    // End of variables declaration//GEN-END:variables
}
