/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.zabalburu.daw1.tmdb.views;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons;
import jiconfont.swing.IconFontSwing;
import org.zabalburu.daw1.tmdb.exceptions.UsuarioNoExisteException;
import org.zabalburu.daw1.tmdb.modelo.Usuario;
import org.zabalburu.daw1.tmdb.servicio.TMDBServicio;
import org.zabalburu.daw1.util.Colores;
import org.zabalburu.daw1.util.PasswordManager;

/**
 *
 * @author ichueca
 */
public class FrmRegistro extends javax.swing.JFrame {
    private String imagen = "no_image.jpg";
    private TMDBServicio servicio = new TMDBServicio();

    /**
     * Creates new form FrmLogin
     */
    public FrmRegistro() {
        initComponents();
        lblFoto.setIcon(new ImageIcon("images/" + imagen));
        lblLogo.setIcon(IconFontSwing.buildIcon(
                GoogleMaterialDesignIcons.PERSON_ADD,
                100, Colores.GREEN));
        //this.getRootPane().setDefaultButton(btnEntrar);
        btnGuardar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlDatos = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblErrorUsuario = new javax.swing.JLabel();
        pwdPassword = new javax.swing.JPasswordField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidps = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblPasswor2 = new javax.swing.JLabel();
        pwdPassword2 = new javax.swing.JPasswordField();
        lblFoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblErrorPassword = new javax.swing.JLabel();
        lblErrorEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro");

        pnlLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 50, 0, 50));
        pnlLogo.setLayout(new javax.swing.BoxLayout(pnlLogo, javax.swing.BoxLayout.LINE_AXIS));

        lblLogo.setPreferredSize(new java.awt.Dimension(180, 0));
        pnlLogo.add(lblLogo);

        getContentPane().add(pnlLogo, java.awt.BorderLayout.LINE_START);

        pnlDatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 30));
        pnlDatos.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("Regístrese");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(14, 0, 9, 9);
        pnlDatos.add(lblTitulo, gridBagConstraints);

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validarDatos(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(14, 9, 9, 0);
        pnlDatos.add(txtUsuario, gridBagConstraints);

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(14, 9, 9, 9);
        pnlDatos.add(btnGuardar, gridBagConstraints);

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalir.setText("Volver");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(14, 9, 9, 9);
        pnlDatos.add(btnSalir, gridBagConstraints);

        lblErrorUsuario.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblErrorUsuario.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorUsuario.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 9, 2, 9);
        pnlDatos.add(lblErrorUsuario, gridBagConstraints);

        pwdPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pwdPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validarDatos(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(14, 9, 9, 0);
        pnlDatos.add(pwdPassword, gridBagConstraints);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmail.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlDatos.add(lblEmail, gridBagConstraints);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validarDatos(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validarDatos(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(14, 9, 9, 0);
        pnlDatos.add(txtEmail, gridBagConstraints);

        lblApellidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblApellidos.setText("Apellidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlDatos.add(lblApellidos, gridBagConstraints);

        txtApellidps.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(14, 9, 9, 0);
        pnlDatos.add(txtApellidps, gridBagConstraints);

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuario.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlDatos.add(lblUsuario, gridBagConstraints);

        lblNombre1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombre1.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlDatos.add(lblNombre1, gridBagConstraints);

        txtNombre1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(14, 9, 9, 0);
        pnlDatos.add(txtNombre1, gridBagConstraints);

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlDatos.add(lblPassword, gridBagConstraints);

        lblPasswor2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPasswor2.setText("Repetir Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlDatos.add(lblPasswor2, gridBagConstraints);

        pwdPassword2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pwdPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdPassword2teclaPulsada(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validarDatos(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(14, 9, 9, 0);
        pnlDatos.add(pwdPassword2, gridBagConstraints);

        lblFoto.setToolTipText("");
        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 134, 152)));
        lblFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFoto.setMinimumSize(new java.awt.Dimension(100, 100));
        lblFoto.setPreferredSize(new java.awt.Dimension(100, 100));
        lblFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFotoMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 0);
        pnlDatos.add(lblFoto, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 1);
        pnlDatos.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 1);
        pnlDatos.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 1);
        pnlDatos.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 1);
        pnlDatos.add(jLabel4, gridBagConstraints);

        lblErrorPassword.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblErrorPassword.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorPassword.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 9, 2, 9);
        pnlDatos.add(lblErrorPassword, gridBagConstraints);

        lblErrorEmail.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblErrorEmail.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorEmail.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 9, 2, 9);
        pnlDatos.add(lblErrorEmail, gridBagConstraints);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(986, 632));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Usuario usuario = new Usuario();
        usuario.setApellido(txtApellidps.getText());
        usuario.setEmail(txtEmail.getText());
        usuario.setImagen(imagen);
        usuario.setNombre(txtNombre1.getText());
        usuario.setPassword(new String(pwdPassword.getPassword()));
        usuario.setUsuario(txtUsuario.getText());
        servicio.nuevoUsuario(usuario);
        JOptionPane.showMessageDialog(this, 
                "Usuario Regbistrado con Éxito!");
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        new FrmLogin().setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void pwdPassword2teclaPulsada(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdPassword2teclaPulsada
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdPassword2teclaPulsada

    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyReleased
        validarDatos(evt);
    }//GEN-LAST:event_txtUsuarioKeyReleased

    private void validarDatos(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validarDatos
        Object cmp = evt.getSource();
        boolean ok = true;
        String usuario = txtUsuario.getText();
        if (usuario.isBlank()) {
            ok = false;
        } else {
            try {
                servicio.getUsuario(usuario);
                // El usuario existe --> ERROR
                lblErrorUsuario.setText("El usuario YA EXISTE!");
                ok = false;
            } catch (UsuarioNoExisteException ex) {
                lblErrorUsuario.setText("");
            }
        }
        String pwd = new String(pwdPassword.getPassword());
        String pwd2 = new String(pwdPassword2.getPassword());
        if (pwd.isBlank() || pwd2.isBlank()) {
            ok = false;
        } else if (!pwd2.isBlank()) {
            if (!pwd.equals(pwd2)) {
                ok = false;
                lblErrorPassword.setText("Las contraseñas no coinciden");
            } else {
                lblErrorPassword.setText("");
            }
        }
        String email = txtEmail.getText();
        if (email.isBlank()) {
            ok = false;
        } else {
            String regex = "^[\\w!#$%&amp;'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&amp;'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$"; // Email
            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(email);
            if (!matcher.matches()) {
                ok = false;
                lblErrorEmail.setText("El email no es válido");
            } else if (!servicio.emailDisponible(email)) {
                ok = false;
                lblErrorEmail.setText("El email ya está registrado!");
            } else {
                lblErrorEmail.setText("");
            }
        }

        btnGuardar.setEnabled(ok);
    }//GEN-LAST:event_validarDatos

    private void lblFotoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoMousePressed
        JFileChooser jfc = new JFileChooser();
        FileFilter filtroImagenes = new FileNameExtensionFilter("Imágenes", 
                ImageIO.getReaderFileSuffixes());
        jfc.setFileFilter(filtroImagenes);
        jfc.setAcceptAllFileFilterUsed(false);
        if (jfc.showOpenDialog(this)
            == 
            JFileChooser.APPROVE_OPTION){
            try {
                File fichero = jfc.getSelectedFile();
                BufferedImage im = ImageIO.read(fichero);
                int max = Math.max(im.getWidth(), im.getHeight());
                double ratio = (double) 100 / max;
                int ancho = (int) (im.getWidth() * ratio);
                int alto = (int) (im.getHeight() * ratio);
                Image imag = im.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
                BufferedImage bi = new BufferedImage(
                        ancho,
                        alto,
                        BufferedImage.TYPE_INT_RGB);
                Graphics2D graphics2D = bi.createGraphics();
                graphics2D.drawImage(imag, 0, 0, null);
                graphics2D.dispose();
                lblFoto.setText("");
                lblFoto.setIcon(new ImageIcon(imag));
                ImageIO.write(bi, "jpg", 
                        new File("images",fichero.getName()));
                imagen = fichero.getName();
            } catch (IOException ex) {
                Logger.getLogger(FrmRegistro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblFotoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        for (String s : ImageIO.getReaderFileSuffixes()){
            System.out.println(s);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblErrorEmail;
    private javax.swing.JLabel lblErrorPassword;
    private javax.swing.JLabel lblErrorUsuario;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblPasswor2;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JPasswordField pwdPassword2;
    private javax.swing.JTextField txtApellidps;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
